feat(argocd-image-updater): Bump application version
argoproj/argo-helm pull request #1017
Opened 2021-11-16 15:23 UTC by nielstenboom

To support the changes made in https://github.com/argoproj/argo-helm/pull/987 , the application version has to be bumped to v0.10.3, as the current version does not have the aws cli embedded in the container yet.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-11-16 23:45 UTC, mkilchhofer requested changes
Can we set the `image.tag` to empty string and only bump the charts appVersion?

2021-11-16 23:45 UTC, mkilchhofer commented on charts/argocd-image-updater/README.md
> +| image.tag | string | `"v0.10.3"` | Default image tag |
```suggestion
| image.tag | string | `""` | Overrides the image tag whose default is the chart appVersion |
```

2021-11-16 23:45 UTC, mkilchhofer commented on charts/argocd-image-updater/Chart.yaml
>  appVersion: v0.10.1
```suggestion
appVersion: v0.10.3
```

2021-11-16 23:45 UTC, mkilchhofer commented on charts/argocd-image-updater/values.yaml
>    # -- Default image tag
```suggestion
  # -- Overrides the image tag whose default is the chart appVersion
```

2021-11-16 23:45 UTC, mkilchhofer commented on charts/argocd-image-updater/values.yaml
> +  tag: v0.10.3
```suggestion
  tag: ""
```

2021-11-17 09:12 UTC, mkilchhofer approved these changes
lgtm. Thanks for your contribution 🙏

2021-11-17 09:14 UTC, mkilchhofer commented
Can you please update against master branch? It doesn't matter if you rebase or merge master to your branch.

If you fork it to your personal account next time, it would help because then we are able to update your branch via GitHub UI. Unfortunately github does not support this for org accounts 😞

2021-11-17 09:42 UTC, nielstenboom commented
Thanks for the review!

> If you fork it to your personal account next time, it would help because then we are able to update your branch via GitHub UI. Unfortunately github does not support this for org accounts 😞

Ah I wasn't aware, will do!

2021-11-17 09:50 UTC, merged