feat(argo-workflows): add support for Deployment annotations
argoproj/argo-helm pull request #1198
Opened 2022-03-25 18:11 UTC by snooyen

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2022-03-28 13:19 UTC, mkilchhofer commented
Related to #1151 but for applicationset istead of workflows

2022-03-28 13:24 UTC, mkilchhofer requested changes

2022-03-28 13:24 UTC, mkilchhofer commented on charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
> +    {{- end }}
wrong indent
```suggestion
  {{- with .Values.controller.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

2022-03-28 13:24 UTC, mkilchhofer commented on charts/argo-workflows/templates/server/server-deployment.yaml
> +    {{- end }}
wrong indent
```suggestion
  {{- with .Values.server.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
```

2022-03-28 13:24 UTC, mkilchhofer commented on charts/argo-workflows/Chart.yaml
> +version: 0.13.2
Let's bump minor version as this PR adds a feature.
```suggestion
version: 0.14.0
```

2022-05-05 17:20 UTC, jmeridth commented
@mkilchhofer can we please get a re-review of this?  We need this in order to use https://github.com/stakater/Reloader.  Thank you @snooyen for getting this PR written up.  Cheers.

2022-05-07 05:59 UTC, jmeridth commented
@mkilchhofer bump

2022-05-09 20:21 UTC, jmeridth commented
@mkilchhofer are you looking for more changes on this PR?

2022-05-09 20:39 UTC, mkilchhofer approved these changes

2022-05-09 20:45 UTC, merged