fix(argo-cd): remove unneeded status from CRD
argoproj/argo-helm pull request #1217
Opened 2022-04-07 01:21 UTC by moustafab

The CRD status field prevents certain tools from using the CRD as is. It should be populated by the api-server.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2022-04-07 09:41 UTC, mbevc1 requested changes
This needs to be addressed upstream (https://github.com/argoproj/applicationset/blob/master/manifests/crds/argoproj.io_applicationsets.yaml#L6566-L6571) first before we change it here in the chart.

2022-04-11 13:53 UTC, moustafab commented
> This needs to be address upstream (https://github.com/argoproj/applicationset/blob/master/manifests/crds/argoproj.io_applicationsets.yaml#L6566-L6571) first before we change it here in the chart.

@mbevc1 That repository has been migrated and the CRD in the argo-cd repository is correct https://github.com/argoproj/argo-cd/blob/master/manifests/crds/applicationset-crd.yaml

2022-04-11 14:22 UTC, mbevc1 commented
Oh, sorry was looking in the wrong place. That's okay and it will follow upstream changes. Thanks for your contribution.

2022-04-11 14:22 UTC, mbevc1 approved these changes

2022-04-11 14:33 UTC, merged