Add cert-manager issuer group support for external issuers
argoproj/argo-helm pull request #1279
Opened 2022-05-16 14:55 UTC by gregsidelinger

Signed-off-by: Greg Sidelinger <sidelig@nationwide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2022-05-18 02:52 UTC, gregsidelinger commented
@mkilchhofer No idea why the chart-test check is not running but I did fix the issue in the docs that was detected last time it ran by running the helm-docs script.  Granted I did need to run jnorwood/helm-docs:v1.9.1 as latest was including comments in the docs and making a general mess of things.

2022-05-18 08:35 UTC, mkilchhofer requested changes
Hi @gregsidelinger 

Let's make it optional as the CRD only requires `name` to be set.

> ```yaml
>                 issuerRef:
>                   description: IssuerRef is a reference to the issuer for this certificate. If the `kind` field is not set, or set to `Issuer`, an Issuer resource with the given name in the same namespace as the Certificate will be used. If the `kind` field is set to `ClusterIssuer`, a ClusterIssuer with the provided name will be used. The `name` field in this stanza is required at all times.
>                   type: object
>                   required:
>                     - name
>                   properties:
>                     group:
>                       description: Group of the resource being referred to.
>                       type: string
>                     kind:
>                       description: Kind of the resource being referred to.
>                       type: string
>                     name:
>                       description: Name of the resource being referred to.
>                       type: string
> ```
> Source: https://github.com/cert-manager/cert-manager/blob/master/deploy/crds/crd-certificates.yaml#L110-L124

Regarding README gen (helm-docs): Already opened an issue upstream https://github.com/norwoodj/helm-docs/issues/148

2022-05-18 08:35 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-server/certificate.yaml
> +    group: {{ .Values.server.certificate.issuer.group | quote }}
```suggestion
    {{- with .Values.server.certificate.issuer.group }}
    group: {{ . | quote }}
    {{- end }}
```

2022-05-19 11:52 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-server/certificate.yaml
> +    {{-end }}
```suggestion
    {{- end }}
```

2022-05-19 11:53 UTC, mkilchhofer approved these changes

2022-05-20 15:55 UTC, mkilchhofer commented on charts/argo-cd/Chart.yaml
> +    - "[Added]: Added support for external issuers for cert-manager"
```suggestion
    - "[Added]: Add support for external issuers in server Certificate resource"
```

2022-05-20 18:10 UTC, merged