fix(argo-cd): argo-cd notifications config map & secret names
argoproj/argo-helm pull request #1299
Opened 2022-05-27 07:32 UTC by Voziv

The notifications controller is hard coded to look for argocd-notifications-secret and argocd-notifications-cm. Unless this changes I think the sane default should be `argocd-notifications-cm` & `argocd-notifications-secret`

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/main/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2022-05-27 18:46 UTC, morey-tech commented on charts/argo-cd/values.yaml
> +    ## If not set the default name 'argocd-notifications-secret' is used
If we are removing `and create is true` in this comment, should it also be removed in the comment for `cm.name`?

2022-06-02 03:40 UTC, Voziv commented
> We only speak about the bot container right?
> 
> All other things should be setup correctly. The name is injected as CLI argument already:

Ah I see. I think the bug may be in the argo-cd notifications code then if it's supposed to be taking the names of the configmap/secret as arguments.

I'm not super well versed in go yet, but I believe it's this line that causes the errors: https://github.com/argoproj/argo-cd/blob/4f155b539b925c2ad732a57fd03a5b5fb8605ae2/cmd/argocd/commands/admin/notifications.go#L33

`settings.GetFactorySettings(argocdService, "argocd-notifications-secret", "argocd-notifications-cm"), func(clientConfig clientcmd.ClientConfig) {`

That said I've noticed that we're still on argocd 2.3.3, I'll try updating our chart version tomorrow morning to see if it's still happening.

2022-06-02 13:45 UTC, Voziv commented
Updating to the latest chart I still get the same error

`time="2022-06-02T13:41:33Z" level=error msg="Failed to process: secret \"argocd-notifications-secret\" not found" resource=argocd/linkerd`

Note: `linkerd` is just the name of an app, every single app name is listed with this error in the argocd-notifications-controller-bot pod


However I do agree with what @mkilchhofer is getting at. This is likely a bug in argo-cd so I'll file a report there. 

In the meantime a fix I can apply myself is overriding the config and secret names using `notifications.cm.name` and `notifications.secret.name` values.

2022-06-02 23:00 UTC, mkilchhofer commented
I also started a discussion in slack over there: https://cloud-native.slack.com/archives/C020XM04CUW/p1654109494458449

2022-06-23 09:30 UTC, gadiener requested changes

2022-06-23 09:30 UTC, gadiener commented on charts/argo-cd/templates/_helpers.tpl
>  {{- if .Values.notifications.secret.create -}}
The if here is probably no longer needed

2022-06-23 09:30 UTC, gadiener commented on charts/argo-cd/templates/_helpers.tpl
>  {{- if .Values.notifications.cm.create -}}
Same here, the if is probably no longer needed

2022-06-23 14:48 UTC, mkilchhofer commented
PR #1340 also fixed things regarding this context here except for the bot

2022-08-25 10:13 UTC, pdrastil commented
Resolved via https://github.com/argoproj/argo-helm/pull/1419

2022-08-25 10:13 UTC, closed without merging