feat(argo-cd): Support annotations in argocd-configs secrets
argoproj/argo-helm pull request #1314
Opened 2022-06-03 14:57 UTC by yu-croco

This PR resolves https://github.com/argoproj/argo-helm/issues/1280 🙋 

---

Signed-off-by: yu-croco <yuki.kita22@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/main/community#contributing-to-argo).
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2022-06-07 08:09 UTC, mkilchhofer requested changes

2022-06-07 08:09 UTC, mkilchhofer commented on charts/argo-cd/README.md
>  | configs.repositoryCredentials | object | `{}` | *DEPRECATED:* Instead, use `configs.credentialTemplates` and/or `configs.repositories` |
`repositoryCredentialSecretAnnotations` follows the deprecated way to configure credentials.
Better use `configs.credentialTemplatesAnnotations` or something similar

2022-06-07 08:09 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-configs/repository-secret.yaml
> +  {{- with $.Values.configs.repositorySecretAnnotations }}
configs.repositoriesAnnotations

2022-06-07 14:10 UTC, yu-croco commented
@mkilchhofer 
Thank you for reviewing! I fixed them on https://github.com/argoproj/argo-helm/pull/1314/commits/8ef71ae664a6124bc5eef388352b825ab3583323 🙋

2022-06-08 06:03 UTC, mkilchhofer approved these changes
Lgtm. Thanks for your contribution, @yu-croco ! Maybe you nominate yourself as a maintainer? :-) -> https://github.com/argoproj/argo-helm/issues/612

2022-06-08 06:03 UTC, merged

2022-06-08 06:12 UTC, yu-croco commented
> Maybe you nominate yourself as a maintainer? :-) -> https://github.com/argoproj/argo-helm/issues/612

Thank you so much!
Yes, I am nominating myself 🙋

2022-06-27 10:39 UTC, yu-croco commented
It looks this PR merged into other project.... 🙄 
I will fix this on this repository.