Feat(argo-cd): Update to Argo CD v2.4.0
argoproj/argo-helm pull request #1325
Opened 2022-06-13 16:20 UTC by minhthong582000

- Upgrade ArgoCD to v2.4.0.

- Specify logs RBAC enforcement config in server. According to this [docs](https://argo-cd.readthedocs.io/en/latest/operator-manual/upgrading/2.3-2.4/#enable-logs-rbac-enforcement): `2.4 introduced logs as a new RBAC resource. In 2.3, users with applications, get access automatically get logs access. In 2.5, you will have to explicitly grant logs, get access.`. So I think we should put the configuration as a reminder to prepare for future releases.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2022-06-13 16:37 UTC, mbevc1 requested changes

2022-06-13 16:37 UTC, mbevc1 commented on charts/argo-cd/values.yaml
> +    server.rbac.log.enforce.enable: "false"
Thanks for your contribution, but this needs to go to CM in the template

2022-06-13 23:29 UTC, minhthong582000 commented on charts/argo-cd/values.yaml
> +  rbacLogEnforce: false
This is exactly what I did in my old commit 😂. I reverted the changes and push it to 14887dcf47c7b9d785c7577b56e0b98edb1ed0f6. Thank you for reviewing.

2022-06-14 07:43 UTC, EugeneLugovtsov commented
@minhthong582000, maybe we should change the image for applicationset from the `quay.io/argoproj/argocd-applicationset` to the `quay.io/argoproj/argocd`?

https://github.com/argoproj/argo-cd/blob/v2.4.0/manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml#L22

2022-06-14 09:28 UTC, mkilchhofer commented
Also merged #1245 and #1266 as their target are 2.4.x

2022-06-14 09:41 UTC, pdrastil commented
@mkilchhofer I've noticed that applicationset controller now have `entrypoint.sh` in the manifest. Maybe this should be added as well. Ref: https://github.com/argoproj/argo-cd/blob/3966e508905037e031f25bf599a3e65c6f4b9fb0/manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml#L20

2022-06-14 09:41 UTC, mkilchhofer approved these changes
Lgtm. Thanks for your contributions @minhthong582000 , @pdrastil and @sathieu

2022-06-14 09:43 UTC, mkilchhofer commented
> @mkilchhofer I've noticed that applicationset controller now have `entrypoint.sh` in the manifest. Maybe this should be added as well. Ref: https://github.com/argoproj/argo-cd/blob/3966e508905037e031f25bf599a3e65c6f4b9fb0/manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml#L20

Nice spotted! Thanks, also added this

2022-06-14 10:08 UTC, mbevc1 approved these changes
Thanks for the changes

2022-06-14 10:10 UTC, merged