[argo-rollouts] add traefikservices resource in role
argoproj/argo-helm pull request #1677
Opened 2022-12-01 10:40 UTC by JuanRamino

Signed-off-by: juan ramino <juan.ramino@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2022-12-01 15:16 UTC, jmeridth commented
Whoops.  Gonna let tests run first.

2022-12-01 18:41 UTC, jmeridth commented
@JuanRamino chart needs a version bump.

2023-01-19 11:01 UTC, mkilchhofer requested changes

2023-01-19 11:01 UTC, mkilchhofer commented on charts/argo-rollouts/Chart.yaml
> +version: 2.21.2
See some lines below, please update the line for the changelog generation

2023-01-19 11:01 UTC, mkilchhofer commented on charts/argo-rollouts/templates/controller/role.yaml
> +  - patch
Can you test with the upstream verbs only (watch, get, update)?

https://github.com/argoproj/argo-rollouts/blob/v1.3.2/manifests/role/argo-rollouts-clusterrole.yaml#L224-L231

2023-01-19 21:16 UTC, mkilchhofer commented
This was fixed/implemented in #1774 already and thus closing this PR here. Feel free to reopen if needed.
Thanks for your contribution anyways. 🙏

2023-01-19 21:16 UTC, closed without merging

2023-01-21 19:42 UTC, JuanRamino commented
Seems fine! Glad to contribute anyway. Thanks