Add parameters to enable/disable creation of Roles and RoleBindings
argoproj/argo-helm pull request #1727
Opened 2022-12-22 18:00 UTC by smartfin

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2022-12-24 19:39 UTC, pdrastil commented
Hi @smartfin, thanks for contribution. Maybe @jmeridth or @mkilchhofer will have different opinion but IMHO I believe this PR only allows user to break the deployment as the RBAC is necessary for proper functionality of controllers and it's generated by build process. If someone want's to provide their own RBAC they will have to copy & paste all that is inside to make controllers work properly. If your intent is to extend RBAC with your own permissions you can always do it via `extraObjects` section.

2022-12-24 19:40 UTC, pdrastil requested changes
Sorry but I consider this as harmful change.

2022-12-28 01:59 UTC, jmeridth commented
@smartfin I concur with @pdrastil on this one.  @mkilchhofer what say you?

2022-12-30 15:18 UTC, mkilchhofer commented
Same from my side. I don't see a change that is related to cluster-level RBAC (only Roles and RoleBindings in this PR, no ClusterRoles and ClusterRoleBindings).

Therefore I'd need a more specific use case to proceed with this PR.

2023-01-04 22:45 UTC, mkilchhofer commented
@smartfin are you sure that that you are not authorized to deploy Roles and RoleBindings? These resources are namespaces and are valid only inside a Namespace.

If so, I assume that you face this "issue" on almost every K8s software who is talking to the kube-apiserver.

2023-01-06 20:25 UTC, smartfin commented
> @smartfin are you sure that that you are not authorized to deploy Roles and RoleBindings? These resources are namespaced and are valid only inside a Namespace.
> 
> If so, I assume that you face this "issue" on almost every K8s software who is talking to the kube-apiserver.

I think I have a very specific use case with a shared cluster with multiple tenants. I think our team will go with another way - render Helm template and filter out specific resources that we are interested in.

2023-01-06 20:26 UTC, closed without merging