Allow to change the log format to json
argoproj/argo-helm pull request #1855
Opened 2023-02-22 13:57 UTC by PuKoren

Currently, the log format is always text causing logs to appear as error on Stackdriver (https://github.com/argoproj/argo-workflows/issues/5135)

The format can be changed since this commit was merged: https://github.com/argoproj/argo-workflows/pull/5158/files
More specifically this line: https://github.com/argoproj/argo-workflows/pull/5158/files#diff-ac70cda72859a5b0b5cdeee97288452ad053332df4b27e37f9647addc0ef510eR72

The change on this PR adds a helm value to control the startup option --log-format 

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2023-02-22 14:48 UTC, yu-croco approved these changes
Thank you for your contribution!
LGTM

2023-02-22 14:59 UTC, pdrastil approved these changes

2023-02-22 20:39 UTC, jmeridth commented
Do we need to do this for server also? On phone so may be silly question.

2023-02-23 03:21 UTC, yu-croco commented
Good catch, @jmeridth ! It sounds nice to make it configureable as well, in the aspect of uniformity.

@PuKoren Can you please add the log format attribute for server as well?

2023-02-23 11:02 UTC, jmeridth commented
@PuKoren @yu-croco I just created [upstream PR](https://github.com/argoproj/argo-workflows/pull/10572) to add log levels to server.  Noticed those were missing.  We can add another PR to the helm chart for that after that PR merges.  Cheers.

2023-02-23 11:02 UTC, jmeridth requested changes
Please add log formatting option for server also.  Thank you.

2023-02-24 09:00 UTC, PuKoren commented
Thanks everyone, I will add it today

2023-02-24 09:21 UTC, PuKoren commented
@jmeridth @yu-croco thanks, I added the changes to the server and also seized the occasion to add the 2 other parameters for log level and global log level. Please let me know if I should remove them for now

2023-02-24 14:03 UTC, PuKoren commented
Sorry about the PR review assignation, I'm not used to it. When I re-request a review from one of you guys it removes everybody else

2023-02-24 14:28 UTC, yu-croco commented
Thank you for updating, @PuKoren ! :) no need to say sorry.
I let the CI run and it seems there are lint violations. 👀 
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/30188755/221202562-c7c91191-3b4b-4639-9ba2-9911a6665316.png">

2023-02-24 18:08 UTC, PuKoren commented
Thank you! My IDE was getting in the way

2023-02-24 21:33 UTC, jmeridth approved these changes

2023-02-24 21:56 UTC, merged