Adding "appProtocol: HTTPS" to HTTPS service port of argocd-server.
argoproj/argo-helm pull request #1861
Opened 2023-02-24 14:41 UTC by hau21um

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2023-02-25 05:24 UTC, mkilchhofer requested changes
Hi @hau21um  thanks for your contribution.
Can you add a description to the PR why we need this?

Upstream manifests don't define this and also some users run the server without TLS ans terminate the TLS session on the ingress, therefore it cannot be hardcoded without a conditional.

2023-03-15 14:29 UTC, hau21um commented
Reasoning behind this. We use Gateway API in GKE, where you can not specify [appProtocol](https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol) using [annotaion](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#def_inf_hc) as with ingress. By default load balancer (LB) health checks will be HTTP  (even the port is 443) and only way to force them to be HTTPs are by using this appProtocol field. And we do not want any unencrypted traffic between LB and our pods.
Also this change is only about setting it on service port 443 called https, so not touching service port 80 called http.

2023-04-11 14:04 UTC, mkilchhofer requested changes

2023-04-11 18:23 UTC, closed without merging

2023-04-11 19:09 UTC, hau21um commented
Sorry, seems I've closed this one by mistake and created new one as  #1955 with suggested conditional templating. Thank you all!.