feat(argo-cd): add parameter env to redis exporter
argoproj/argo-helm pull request #1876
Opened 2023-03-02 12:08 UTC by cgroschupp

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

Changes are automatically published when merged to `main`. They are not published on branches.

2023-03-02 13:38 UTC, mkilchhofer requested changes

2023-03-02 13:38 UTC, mkilchhofer commented on charts/argo-cd/Chart.yaml
>        description: Indentation for argo-server role when exec.enabled is True.
these lines need to be removed

2023-03-02 13:51 UTC, cgroschupp commented on charts/argo-cd/Chart.yaml
>        description: Indentation for argo-server role when exec.enabled is True.
Sorry, I misunderstood.

2023-03-09 08:24 UTC, pdrastil approved these changes

2023-03-09 11:37 UTC, cgroschupp commented
@pdrastil done

2023-03-09 12:00 UTC, mbevc1 approved these changes

2023-03-09 12:05 UTC, merged