Add possibility to configure healthz and metrics ports to be compatible with Istio
argoproj/argo-helm pull request #1976
Opened 2023-04-23 17:22 UTC by Hronom

Add possibility to configure healthz and metrics ports to be compatible with Istio

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2023-05-06 11:06 UTC, jmeridth requested changes
This all LGTM, just need to update the Chart.yaml version.  Then we can re-run tests and get this merged.  Thank you for your contribution.

2023-05-07 22:59 UTC, Hronom commented
@jmeridth Updated, also I'm ok if maintainers do adjustments in this PR. So it will not be open 2 weeks because of to need bump version or whatever other reasons.

Thanks!

2023-05-08 03:22 UTC, jmeridth commented on charts/argo-cd/Chart.yaml
>  name: argo-cd
@Hronom this is the wrong chart file.  Needs to be `charts/argo-rollouts/Chart.yaml` 😄

2023-05-08 03:27 UTC, jmeridth submitted a review, later dismissed

2023-05-08 05:17 UTC, mkilchhofer commented
Hi @Hronom 
Thanks for your contribution.
Are you really sure that istio needs this on Deployment level?
I know that this can be needed on `kind: Service` but it's new to me that its also required on the Pods itself.

Aside this, can you take a look into the argo-cd chart and follow the same style for the variable names:
- Values.controller.containerPorts.metrics
- Values.controller.metrics.service.portName
- Values.controller.metrics.service.servicePort

2023-05-14 23:06 UTC, Hronom commented
@mkilchhofer 
> Are you really sure that istio needs this on Deployment level?
I know that this can be needed on kind: Service but it's new to me that its also required on the Pods itself.

I'm just added to align names, seems to be not needed https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

> Aside this, can you take a look into the argo-cd chart and follow the same style for the variable names:

The names that I set:
```
  - name: {{ .Values.controller.metrics.service.portName }}
    protocol: TCP
    port: {{ .Values.controller.metrics.service.port }}
    targetPort: {{ .Values.controller.metrics.service.targetPort }}
```
same as in `dashboard`:
```
  - name: {{ .Values.dashboard.service.portName }}
    protocol: TCP
    port: {{ .Values.dashboard.service.port }}
    targetPort: {{ .Values.dashboard.service.targetPort }}
```
so I assume it's standard here?

But I'm ok if maintainers change them

2023-05-19 12:26 UTC, yu-croco commented on charts/argo-rollouts/Chart.yaml
>        description: Introduce chart signing
Please remove old change logs 🙋

2023-05-19 12:30 UTC, yu-croco commented on charts/argo-rollouts/values.yaml
> +  containerPorts:
Maybe better to add comment to show description on README.md? 🙋 

```diff
+# -- Controller container ports
containerPorts:
    metrics: 8090
    healthz: 8080
```

2023-05-19 12:33 UTC, jmeridth submitted a review, later dismissed

2023-05-19 12:34 UTC, yu-croco commented on charts/argo-rollouts/values.yaml
> +      port: 8090
please also add comment like https://github.com/argoproj/argo-helm/pull/1976/files#r1198905565. 🙏

2023-05-19 17:56 UTC, Hronom commented
@yu-croco , @jmeridth added changes

2023-05-19 19:04 UTC, mkilchhofer reviewed
Thank you so much for implementing all requested changes 💯 
One last change request:
As this PR adds a feature, according to semver you need to bump the minor chart version.

As soon as its implemented, I'll approve it and merge this PR

2023-05-20 15:26 UTC, Hronom commented
@mkilchhofer done

2023-05-20 15:27 UTC, yu-croco approved these changes
Thank you for your contribution! LGTM.

2023-05-20 15:38 UTC, mkilchhofer approved these changes
💯

2023-05-20 15:39 UTC, jmeridth approved these changes

2023-05-20 15:39 UTC, merged