fix(argo-workflows): Fix Helm chart to correctly reference Kubernetes version in conditional check for HPA apiVersion
argoproj/argo-helm pull request #2029
Opened 2023-05-08 13:43 UTC by ryanpark0203

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2023-05-08 13:46 UTC, jmeridth commented
@ryanpark0203 great catch.  Thank you for the contribution.  To satisfay DCO you need to sign your commits.  I'll kick off tests once that's done.

2023-05-09 00:37 UTC, yu-croco commented on charts/argo-workflows/values.yaml
> +  autoscaling: "" # autoscaling/v2
nits:
We don't need to show the following row on README, 
```
| apiVersionOverrides | object | `{"autoscaling":""}` | Override APIVersions |
```

so maybe like this?
```diff
-# -- Override APIVersions
apiVersionOverrides:
  # -- String to override apiVersion of autoscaling rendered by this helm chart
  autoscaling: "" # autoscaling/v2
```

or 

```diff
-# -- Override APIVersions
+# Override APIVersions
apiVersionOverrides:
  # -- String to override apiVersion of autoscaling rendered by this helm chart
  autoscaling: "" # autoscaling/v2
```

2023-05-09 03:28 UTC, jmeridth approved these changes

2023-05-09 03:28 UTC, jmeridth requested changes

2023-05-09 03:28 UTC, jmeridth commented on charts/argo-workflows/Chart.yaml
> +    - kind: fix
fix -> fixed

2023-05-09 03:33 UTC, jmeridth approved these changes

2023-05-09 03:41 UTC, yu-croco approved these changes

2023-05-09 03:41 UTC, merged