feat(argo-cd): Add ability to add certificate to Argo CD Controller
argoproj/argo-helm pull request #2052
Opened 2023-05-11 13:02 UTC by yu-croco

Resolves https://github.com/argoproj/argo-helm/issues/2028 🙋 

---

Signed-off-by: yu-croco <yu.croco@gmail.com>

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2023-05-11 13:03 UTC, yu-croco commented on charts/argo-cd/values.yaml
> +  certificate:
same as [server's definition](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml#L1696-L1730) 🙋

2023-05-11 13:04 UTC, yu-croco commented on charts/argo-cd/templates/argocd-application-controller/certificate.yaml
> +{{- if .Values.controller.certificate.enabled -}}
same as https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/argocd-server/certificate.yaml 🙋

2023-05-11 14:27 UTC, mkilchhofer requested changes
Hi @yu-croco
You implemented it in the "wrong" controller.

The issue wants that feature on the ApplicationSET controller not the normal controller :-)

2023-05-11 15:08 UTC, yu-croco commented
Hi @mkilchhofer , thank you for your review.
I fixed on https://github.com/argoproj/argo-helm/pull/2052/commits/8f8049499e5ce22a154444a940fca2fb5fa24213 🙋

2023-05-12 10:58 UTC, mbevc1 approved these changes

2023-05-12 18:43 UTC, jmeridth approved these changes

2023-05-13 11:01 UTC, mkilchhofer approved these changes

2023-05-13 11:01 UTC, merged