Add missing cluster rolebinding for applicationset in case multiple namespaces are used.
argoproj/argo-helm pull request #2227
Opened 2023-08-17 15:41 UTC by borisssmidtCET

I recently enabled the name spacing feature of the application controller and ran into the the issue that the application controller couldn't create/read the applications in the required namespace.

Its probably best to add a cluster role for this case?

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2023-08-17 22:48 UTC, jmeridth commented
Please fix your PR title to match requirement of

example: `fix(argo-cd): blah blah blah`

Also please sign all of your commits to pass DCO.  Thanks.

2023-08-18 07:36 UTC, yu-croco commented
Hi @borisssmidtCET , thank you for your PR.
Please handle below (items written in PR description).

> [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)

-> Please bump patch version.

> [ ] I have updated the chart [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog) with all the changes that come with this pull request according to changelog.

-> Please remove old ones and add new ones in [changelog](https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/Chart.yaml#L28).

2023-08-18 11:18 UTC, mkilchhofer requested changes

2023-08-18 11:18 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-applicationset/clusterrolebinding.yaml
> +{{- $config := .Values.controller.clusterAdminAccess | default dict -}}
Please remove the backward compat from the old param of the application-controller. It doesn't make sense to add something from the other controller (application-controller vs. applicationSET-controller) here.

2023-08-18 11:18 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-applicationset/clusterrole.yaml
> +{{- $config := .Values.controller.clusterAdminAccess | default dict -}}
Please remove the backward compat from the old param of the application-controller. It doesn't make sense to add something from the other controller (application-controller vs. applicationSET-controller) here.

2023-08-21 19:27 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-application-controller/clusterrolebinding.yaml
> -{{- if hasKey $config "enabled" | ternary $config.enabled .Values.createClusterRoles }}
Please restore the change on the application-controller. We still need backward compat on this one.

2023-08-21 19:29 UTC, mkilchhofer requested changes

2023-08-21 19:29 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-applicationset/clusterrolebinding.yaml
> +{{- if hasKey $config "enabled" | ternary $config.enabled .Values.createClusterRoles }}
Ah maybe you mixed up some things. This one doesn't need backward compat.

2023-11-27 12:49 UTC, sadoMasupilami commented
Hi, I think this is still relevant! Is there anything to be done to get this going again?

2023-12-25 07:59 UTC, mugioka commented
i will be create pr for that.

2023-12-26 02:33 UTC, mugioka commented
https://github.com/argoproj/argo-helm/pull/2402

2024-02-23 17:24 UTC, jmeridth commented
Closing in favor of #2502 as it has recent interactions and movement.  Thank you for contributing @borisssmidtCET.

2024-02-23 17:24 UTC, closed without merging