docs: Update docs with the correct default for application.instanceLabelKey
argoproj/argo-helm pull request #2447
Opened 2024-01-22 18:14 UTC by bodgit

Noticed the documented default didn't match the chart default. As this is just documentation I haven't bumped any versions.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2024-01-22 18:15 UTC, tico24 commented
Still needs a version bump please. Otherwise it can't be released.

2024-01-22 19:56 UTC, mkilchhofer requested changes

2024-01-22 19:56 UTC, mkilchhofer commented on charts/argo-cd/values.yaml
> +    # @default -- Defaults to argocd.argoproj.io/instance
Can we remove that line completely and run helm-docs in the scripts folder? This way, the default is automatically updated from the real value

2024-01-22 22:46 UTC, mkilchhofer approved these changes
LGTM. Thanks for your contribution @bodgit ! 🙏

2024-01-22 23:55 UTC, yu-croco approved these changes

2024-01-23 00:12 UTC, yu-croco approved these changes

2024-01-23 01:07 UTC, yu-croco approved these changes

2024-01-23 01:07 UTC, merged