chore(argo-rollouts): Change controller deployment strategy to rollinUpdate
argoproj/argo-helm pull request #2572
Opened 2024-03-03 14:55 UTC by ilyastoliar

Signed-off-by: Ilya Stoliar <ilyast@monday.com>

Change controller deployment strategy to rollingUpdate due to chore: change controller's deploy strategy to RollingUpdate due to leader election #3334
https://github.com/argoproj/argo-rollouts/pull/3334/

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2024-03-03 14:59 UTC, navele approved these changes

2024-03-03 15:00 UTC, alonbehaim approved these changes

2024-03-03 15:01 UTC, shaharfreidenberg approved these changes

2024-03-03 16:15 UTC, jmeridth commented
Thank you for your contribution.  Unfortunately, https://github.com/argoproj/argo-rollouts/pull/3334 is merged but not released, so we can't apply it to the helm chart yet.  There was a release after it was merged but it did not include the change.

Also https://github.com/argoproj/argo-helm/pull/2412 is the more configurable approach.

2024-03-03 16:16 UTC, jmeridth requested changes
Thank you for your contribution but I believe #2412 is the better approach and we're still waiting for upstream to release the change also.

2024-03-03 21:24 UTC, yu-croco commented
Hi @ilyastoliar , thank you for your PR. I agree with @jmeridth .

2024-03-25 07:20 UTC, mkilchhofer commented
Closing this in favor of https://github.com/argoproj/argo-helm/pull/2412

2024-03-25 07:20 UTC, closed without merging