Fix secretName for server and applicationSet Certificates
argoproj/argo-helm pull request #2741
Opened 2024-06-04 11:34 UTC by erwanval

argocd-server and argocd-applicationset are expecting a secret with a predefined name, so having the option to set a custom name for the secret is confusing.

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [x] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2024-06-04 15:27 UTC, jmeridth commented
The default values that are assigned match the default values.  You do not need to have them in your values.yaml and the default values will be set.  I'm not a fan of this PR but await feedback from other maintainers.

2024-06-04 19:33 UTC, mkilchhofer requested changes
I have no strict opinion here. I am fine with both.

But the changelog is wrong (you mentioned the wrong parameters).

2024-06-04 19:33 UTC, mkilchhofer commented on charts/argo-cd/Chart.yaml
> +      description: Remove server.certificate.serverName, as the expected secret name is static (argocd-server-tls)
```suggestion
      description: Remove `server.certificate.secretName`, as the expected secret name is static (argocd-server-tls)
```

2024-06-04 19:33 UTC, mkilchhofer commented on charts/argo-cd/Chart.yaml
> +      description: Remove applicationSet.certificate.serverName, as the expected secret name is static (argocd-applicationset-controller-tls)
```suggestion
      description: Remove `applicationSet.certificate.secretName`, as the expected secret name is static (argocd-applicationset-controller-tls)
```

2024-06-05 17:27 UTC, jmeridth commented
Closing and reopening to see if DCO kicks off (was off and is on again)

2024-06-05 17:34 UTC, jmeridth commented
Queue might be backed up still due to https://github.com/dcoapp/app/issues/211.  Can try again later.

2024-06-05 18:13 UTC, jmeridth commented
@erwanval when you make the changes requested by @mkilchhofer, maybe a new commit will trigger the DCO app.  We'll see.

2024-06-10 11:45 UTC, erwanval commented
> The default values that are assigned match the default values. You do not need to have them in your values.yaml and the default values will be set. I'm not a fan of this PR but await feedback from other maintainers.

If you keep the default, it works indeed. However, any other values than the default will be ignored, and the application will generate its own self-signed certificate instead. It still starts without error in appearance, but can cause confusion since the exposed cert doesn't match the one you configured.

@mkilchhofer Thanks for fixing the typo in changelog.
Regarding DCO, it seems to have been triggered now, but there is no "Verified" next to my commits somehow? I'm not sure if I'm missing something, it usually works just fine with other repositories.

2024-06-10 17:28 UTC, mkilchhofer commented
> Regarding DCO, it seems to have been triggered now, but there is no "Verified" next to my commits somehow? I'm not sure if I'm missing something, it usually works just fine with other repositories.

DCO is perfectly fine now (green rectangles). It was failing as the DCO GitHub app was not okay.
![image](https://github.com/argoproj/argo-helm/assets/7290987/4b7a3c01-3156-4c6e-8f5e-886dad54c2ce)

(The verified commits (gpg key or via GitHub GUI) are not required in argo-helm) :)

2024-06-18 10:28 UTC, mkilchhofer approved these changes

2024-06-18 11:02 UTC, mbevc1 approved these changes

2024-06-18 11:52 UTC, yu-croco commented
Hi @erwanval , can you please resolve conflict?

2024-06-19 08:42 UTC, erwanval commented
@yu-croco done, thanks

2024-06-20 10:25 UTC, yu-croco approved these changes

2024-06-20 10:25 UTC, merged