fix(argocd-apps): don't render empty app description
argoproj/argo-helm pull request #2911
Opened 2024-09-04 16:32 UTC by reegnz

Signed-off-by: Zoltán Reegn <zoltan.reegn@gmail.com>

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#versioning)
* [ ] I have updated the documentation according to [documentation](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#documentation)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/main/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md).
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/)).

2024-09-04 22:08 UTC, mkilchhofer approved these changes

2024-09-04 22:48 UTC, yu-croco submitted a review, later dismissed

2024-09-04 23:15 UTC, yu-croco commented
Hi @reegnz , thank you for your PR.
Please fix lint ( https://github.com/argoproj/argo-helm/actions/runs/10705865587/job/29697905648?pr=2911 ), otherwise LGTM.

2024-09-10 19:56 UTC, mkilchhofer requested changes

2024-09-10 19:56 UTC, mkilchhofer commented on charts/argocd-apps/Chart.yaml
> +    - kind: fixed
```suggestion
    - kind: fixed
```

2024-09-10 19:57 UTC, mkilchhofer approved these changes

2024-09-10 21:55 UTC, yu-croco approved these changes

2024-09-10 21:55 UTC, merged