fix(argo): Update minio chart to solve install error
argoproj/argo-helm pull request #495
Opened 2020-11-12 14:00 UTC by mszostok

Checklist:

* [x] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

2020-11-12 14:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-helm?pullRequest=495) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-helm?pullRequest=495) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-helm?pullRequest=495) it.</sub>

2020-12-15 20:51 UTC, stefansedich requested changes
Few small changes and this should be good to get in! apologies for the delay missed this one.

2020-12-15 20:51 UTC, stefansedich commented on scripts/publish.sh
>  helm repo add stable https://kubernetes-charts.storage.googleapis.com
We can probably remove this right?

2020-12-15 20:51 UTC, stefansedich commented on charts/argo/Chart.yaml
> +version: 0.13.3
Can you bump to the next chart version, think it is 0.14.1 at this point.

2020-12-17 07:46 UTC, cabrinha commented
I could be wrong but, now that [apiVersion](https://github.com/argoproj/argo-helm/blob/master/charts/argo/Chart.yaml#L1) is `v2`: the requirements.yaml and requirements.lock files need to be deleted. The "dependencies" list needs to be moved into Chart.yaml

2021-03-29 14:21 UTC, mszostok commented
I tested the `0.16.7` Argo Helm Chart version and the MinIO bug is fixed, so I'm closing this PR.

2021-03-29 14:21 UTC, closed without merging