Bump dex image for secretEnv in staticClients to work
argoproj/argo-helm pull request #519
Opened 2020-12-12 18:24 UTC by hobbsh

The dex image needs to be bumped to `v2.26.0` for `staticClients.secretEnv` to work. For reference, this is the full config I'm using to have Argo Workflows share the Argo CD Okta SSO connector:

argo-cd/values.yaml:
```
     dex:
       image:
         tag: v2.26.0
       env:
         - name: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
           valueFrom:
             secretKeyRef:
               name: argo-workflows-sso
               key: client-secret
...
     server:
       config:
           staticClients:
           - id: argo-workflows-sso
             name: Argo Workflow
             redirectURIs:
               - https://argo-workflows.mydomain.com/oauth2/callback
             secretEnv: ARGO_WORKFLOWS_SSO_CLIENT_SECRET
```

argo/values.yaml:
```
     server:
       extraArgs:
         - --auth-mode=sso
       sso:
         issuer: https://argo-cd.mydomain.com/api/dex
         clientId:
           name: argo-workflows-sso
           key: client-id
         clientSecret:
           name: argo-workflows-sso
           key: client-secret
         redirectUrl: https://argo-workflows.mydomain.com/oauth2/callback
```

Checklist:

* [X] I have update the chart version in `Chart.yaml` following Semantic Versioning.
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [X] I have signed the CLA and the build is green.
* [X] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

2021-01-21 18:38 UTC, alexec requested changes
Please rebase.

2021-01-22 00:31 UTC, hobbsh commented
> Please rebase.

All set

2021-01-23 09:59 UTC, davidkarlsen approved these changes

2021-01-23 10:01 UTC, davidkarlsen approved these changes

2021-01-23 10:11 UTC, davidkarlsen commented
I think @alexec needs to click the "resolve conversion" button

2021-01-25 18:13 UTC, spencergilbert approved these changes

2021-01-26 06:36 UTC, merged