feat(argo-events): add priorityClassName and podLabels options
argoproj/argo-helm pull request #610
Opened 2021-03-04 08:32 UTC by t3mi

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

2021-04-24 10:57 UTC, oliverbaehler commented
@t3mi Thanks for your contribution, Sorry that it took some time for someone to review it. Could you pull the latest master and resolve potential conflicts and bump to a new version? After I can merge it :)

2021-04-26 11:09 UTC, t3mi commented
@oliverbaehler done.

2021-04-26 11:15 UTC, oliverbaehler requested changes
I also recommend using `with`, since you achieve the same affect but don't have to write the same value path twice. If you could accept the suggestions for the sake of consistency :rotating_light:

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/sensor-controller-deployment.yaml
> +      priorityClassName: {{ .Values.sensorController.priorityClassName | quote }}
```suggestion
      {{- with .Values.sensorController.priorityClassName }}
      priorityClassName: {{ . | quote }}
```

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/sensor-controller-deployment.yaml
> +        {{- tpl (toYaml .Values.sensorController.podLabels) $ | nindent 8 }}
```suggestion
        {{- with .Values.sensorController.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
```

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/eventsource-controller-deployment.yaml
> +      priorityClassName: {{ .Values.eventsourceController.priorityClassName | quote }}
```suggestion
      {{- with .Values.eventsourceController.priorityClassName }}
      priorityClassName: {{ . | quote }}
```

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/eventsource-controller-deployment.yaml
> +        {{- tpl (toYaml .Values.eventsourceController.podLabels) $ | nindent 8 }}
```suggestion
        {{- with .Values.eventsourceController.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
```

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/eventbus-controller-deployment.yaml
> +      priorityClassName: {{ .Values.eventbusController.priorityClassName | quote }}
```suggestion
      {{- with .Values.eventbusController.priorityClassName }}
      priorityClassName: {{ . | quote }}
```

2021-04-26 11:15 UTC, oliverbaehler commented on charts/argo-events/templates/eventbus-controller-deployment.yaml
> +        {{- tpl (toYaml .Values.eventbusController.podLabels) $ | nindent 8 }}
```suggestion
        {{- with .Values.eventbusController.podLabels }}
        {{- tpl (toYaml .) $ | nindent 8 }}
```

2021-04-26 12:34 UTC, oliverbaehler approved these changes
lgtm

2021-04-26 12:35 UTC, merged