fix (argocd-notifications): By default, the creation of a Slack notification service is disabled.
argoproj/argo-helm pull request #635
Opened 2021-03-25 15:34 UTC by 1Psy

Checklist:

* [x ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed the CLA and the build is green.
* [x] I will test my changes again once merged to master and published.

Changes are automatically published when merged to `master`. They are not published on branches.

2021-04-21 09:44 UTC, oliverbaehler commented
@1Psy Hi, Thanks for your contribution. Could you give some more context on why this should not be commented in the default values?

2021-04-21 10:35 UTC, 1Psy commented
@oliverbaehler Hi. I would like to disable it because it records to CM even if I use another notifier.
![slack](https://user-images.githubusercontent.com/41047934/115540126-6ce2b600-a2a6-11eb-9699-2b102b3b4dc9.jpg)

2021-04-24 10:53 UTC, oliverbaehler requested changes
Verison Bump

2021-04-24 10:53 UTC, oliverbaehler commented on charts/argocd-notifications/Chart.yaml
> +version: 1.0.16
```suggestion
version: 1.1.3
```

2021-04-24 19:00 UTC, closed without merging

2021-04-24 19:03 UTC, 1Psy commented
I want to refactor the chat and add this in the future.