Sync ArgoCD helm chart with kustomize
argoproj/argo-helm pull request #659
Opened 2021-04-08 11:57 UTC by mhoyer

Checklist:

* [x] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

This is a patch for #645. It syncs some missing parts I mentioned in https://github.com/argoproj/argo-helm/pull/645#issuecomment-815690433 from the original https://github.com/argoproj/argo-cd/blob/v2.0.0/manifests/install.yaml.

2021-04-08 11:59 UTC, mhoyer commented
⚠️ I am not sure about and need some advice:

1. Is this update of the helm chart version in this PR really just a patch? Because of redis image version change. Or better a 3.1.0?
2. We faced some issues on our Tanzu Kubernetes clusters (TKGI) with that redis version 6.2.x not being able to start (not possible to bind to TCP). It seems to be related to the redis docker image and maybe just in constellation with our Kubernetes setup.

2021-04-08 12:28 UTC, davidkarlsen approved these changes

2021-04-08 12:31 UTC, davidkarlsen commented
> ⚠️ I am not sure about and need some advice:
> 
> 1. Is this update of the helm chart version in this PR really just a patch? Because of redis image version change. Or better a 3.1.0?

I think it's fine since it's just a third-party and doesn't affect argo as such.

> 2. We faced some issues on our Tanzu Kubernetes clusters (TKGI) with that redis version 6.2.x not being able to start (not possible to bind to TCP). It seems to be related to the redis docker image and maybe just in constellation with our Kubernetes setup.

Is this tied to tanzu / the env, or are additional actions needed?

2021-04-08 14:55 UTC, mhoyer commented
> Is this tied to tanzu / the env, or are additional actions needed?

I found the reason, which seems to be an issue with newer Redis 6 and our TKGI installation - but may affect other setups as well. 

It seems with Redis 6 the default TCP binding behavior is [as documented](https://raw.githubusercontent.com/redis/redis/6.0/redis.conf):

> ```
> # By default, if no "bind" configuration directive is specified, Redis listens
> # for connections from all available network interfaces on the host machine.
> ```

As the Redis docker image does not have any default configuration it tries to bind to all interfaces - including the IPv6 interface `::1`. This results in this error we found at the end of our logs:

```bash
$ kubectl logs argocd-redis-59b5c586b6-rsdn2
1:C 08 Apr 2021 14:32:02.255 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 08 Apr 2021 14:32:02.255 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 08 Apr 2021 14:32:02.255 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 08 Apr 2021 14:32:02.256 * monotonic clock: POSIX clock_gettime
1:M 08 Apr 2021 14:32:02.260 # Could not create server TCP listening socket ::*:6379: unable to bind socket, errno: 97
```

I was able to fix it by extending the `args` array inside the template of [`deployment.yaml` of the Redis component](https://github.com/argoproj/argo-helm/blob/3b0ebdda661d8ff73ce2179fcf4adfdcc09c87bb/charts/argo-cd/templates/redis/deployment.yaml#L39) by adding `--bind 127.0.0.1`. Like so:

```yaml
...
      containers:
      - name: {{ template "argo-cd.redis.fullname" . }}
        args:
        - --save
        - "''"
        - --appendonly
        - "no"
        - --bind
        - "127.0.0.1"
```

Now the issue is, that there is currently no good way of fixing this from the "outside" of the chart (not in the template itself). I am actually missing something like the `extraArgs` parameter we already see for the [ArgoCD Server component](https://github.com/argoproj/argo-helm/blob/3b0ebdda661d8ff73ce2179fcf4adfdcc09c87bb/charts/argo-cd/templates/argocd-server/deployment.yaml#L61).

Shall I try to extend this PR with this `extraArgs` capability for `redis` section?

2021-04-08 15:27 UTC, ArgTang commented
@mhoyer Could you add a section to the readme to describe where to find the kustomize resources and the command to sync it? Would be helpful for next time :)

2021-04-09 07:28 UTC, mhoyer commented
@ArgTang I hope these notes in https://github.com/argoproj/argo-helm/pull/659/commits/7b3d640a6a02a3d3a43d814053e5fab6f2bf291a make sense to you?

2021-04-16 12:18 UTC, mhoyer commented
Is there anything I can support one of the maintainers here further?

2021-04-23 23:45 UTC, oliverbaehler requested changes
Please bump the chart version and we will merge this asap 🍡

2021-04-23 23:45 UTC, oliverbaehler commented on charts/argo-cd/Chart.yaml
> +version: 3.1.2
```suggestion
version: 3.2.2
```

2021-04-24 10:50 UTC, oliverbaehler approved these changes
lgtm

2021-04-24 10:50 UTC, merged