add service account to argocd notifications
argoproj/argo-helm pull request #673
Opened 2021-04-13 00:20 UTC by cesarokuti

Signed-off-by: Cesar Okuti <cesar.okuti@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-04-13 01:25 UTC, romulofranca approved these changes

2021-04-21 13:22 UTC, oliverbaehler requested changes
Please Bump to Chart Version `1.1.2`

2021-04-26 12:37 UTC, oliverbaehler requested changes
Bump Chart Version and Replace `if` statement.

2021-04-26 12:37 UTC, oliverbaehler commented on charts/argocd-notifications/templates/bots/slack/serviceaccount.yaml
> +    {{- toYaml .Values.bots.slack.serviceAccount.annotations | nindent 4 }}
```suggestion
  {{- with .Values.bots.slack.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
```

2021-04-26 12:37 UTC, oliverbaehler commented on charts/argocd-notifications/templates/serviceaccount.yaml
> +    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
```suggestion
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
```

2021-05-26 21:38 UTC, mkilchhofer approved these changes
LGTM

2021-05-26 21:41 UTC, merged