feat(argo-events): Add annotations to argo-events-sa.
argoproj/argo-helm pull request #708
Opened 2021-05-03 17:07 UTC by kostas-theo

This is a small feature to allow the passing in of Kubernetes Service Account (KSA) annotations into the `argo-events-sa` service account. Currently this is not possible using this chart. This is desired to be able to use the already created KSA with GKE workload identity, as well as any other use cases people may have using annotations.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have updated the chart version in `Chart.yaml` following Semantic Versioning.
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have followed the testing instructions in the [contributing guide](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md).
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-05-09 20:12 UTC, oliverbaehler submitted a review, later dismissed
You haven't bumped the chart version.

2021-05-09 20:12 UTC, oliverbaehler commented on charts/argo-events/templates/argo-events-sa.yaml
> +  annotations: {{- toYaml .Values.serviceAccountAnnotations | nindent 4 }}
```suggestion
  {{- with .Values.serviceAccountAnnotations }}
  annotations: {{- toYaml . | nindent 4 }}
```

2021-05-09 20:12 UTC, oliverbaehler commented on charts/argo-events/templates/argo-events-sa.yaml
> +  annotations: {{- toYaml $annotations | nindent 4 }}
```suggestion
  {{- with $annotations }}
  annotations: {{- toYaml . | nindent 4 }}
```

2021-05-26 21:20 UTC, mkilchhofer requested changes

2021-05-26 21:20 UTC, mkilchhofer commented on charts/argo-events/templates/argo-events-sa.yaml
> +  annotations: {{- toYaml .| nindent 4 }}
```suggestion
  annotations: {{- toYaml . | nindent 4 }}
```

2021-05-26 21:22 UTC, mkilchhofer approved these changes
LGTM

2021-05-26 21:27 UTC, merged