feat: Add support for extra containers in server & controller deployment
argoproj/argo-helm pull request #841
Opened 2021-07-20 13:38 UTC by mikebryant

My use-case for this is using persistence with a GCP CloudSQL database, using the sidecar pattern for the cloud-sql-proxy

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-07-20 13:48 UTC, mikebryant commented
Some basic testing:
```
mikebryant@BULB-MB-0246 argo-workflows % cat env.yaml
server:
  extraContainers:
    - name: blah
      image: blah
mikebryant@BULB-MB-0246 argo-workflows % helm template . --values env.yaml | tail
          - name: tmp
            mountPath: /tmp

        - image: blah
          name: blah
      volumes:
      - name: tmp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
```

2021-08-10 21:46 UTC, oliverbaehler requested changes

2021-08-10 21:46 UTC, oliverbaehler commented on charts/argo-workflows/templates/controller/workflow-controller-deployment.yaml
> +        {{- end }}
```suggestion
        {{- with .Values.controller.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
```

2021-08-10 21:46 UTC, oliverbaehler commented on charts/argo-workflows/templates/server/server-deployment.yaml
> +        {{- end }}
```suggestion
        {{- with .Values.server.extraContainers }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
```

2021-08-10 22:26 UTC, mikebryant commented
Thanks for the review, have applied the requested changes :)

2021-08-11 07:28 UTC, oliverbaehler approved these changes
lgtm

2021-08-11 07:32 UTC, merged