fix(argo-rollouts): missing liveness and readiness probe
argoproj/argo-helm pull request #860
Opened 2021-08-07 02:59 UTC by huikang

Signed-off-by: Hui Kang <hui.kang@salesforce.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-08-08 17:17 UTC, huikang commented
Refer to https://github.com/argoproj/argo-rollouts/blob/cf19b5b88089adcf4cc0b493de2db232cfb9181c/manifests/base/argo-rollouts-deployment.yaml#L26-L42

2021-08-09 14:49 UTC, huikang commented
Hi, @mkilchhofer , could you help review this PR or shall I ping someone else? Thanks.

2021-08-09 17:54 UTC, mkilchhofer commented
> Hi, @mkilchhofer , could you help review this PR or shall I ping someone else? Thanks.

I do not use the rollouts project, so I can only support with helm related stuff here. But I think I'd move the full liveness/readiness probes to values like this:
```yaml
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- omit .Values.livenessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- omit .Values.readinessProbe "enabled" | toYaml | nindent 12 }}
          {{- end }}
```
WDYT?

2021-08-09 18:26 UTC, huikang commented
Hi, @mkilchhofer , thanks for reviewing. The PR is updated as you suggested, except for always enabling the liveness and readiness probe which I believe are desired feature like in other projects, e.g., argo-cd deployment.

2021-08-10 06:17 UTC, mkilchhofer requested changes

2021-08-10 06:17 UTC, mkilchhofer commented on charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
> +          {{- .Values.controller.livenessProbe | toYaml | nindent 10 }}
```suggestion
          {{- toYaml .Values.controller.livenessProbe | nindent 10 }}
```

2021-08-10 06:17 UTC, mkilchhofer commented on charts/argo-rollouts/templates/argo-rollouts-deployment.yaml
> +          {{- .Values.controller.readinessProbe | toYaml | nindent 10 }}
```suggestion
          {{- toYaml .Values.controller.readinessProbe | nindent 10 }}
```

2021-08-10 06:31 UTC, mkilchhofer approved these changes

2021-08-10 06:35 UTC, mkilchhofer commented on charts/argo-rollouts/Chart.yaml
>  icon: https://raw.githubusercontent.com/argoproj/argo/master/argo.png
```suggestion
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
```

2021-08-10 06:35 UTC, mkilchhofer commented on charts/argo-rollouts/Chart.yaml
> +    - "[Fixed]: Add missing liveness and readiness probes"
```suggestion
    - "[Fixed]: Add missing liveness and readiness probes"
    - "[Changed]: Fix icon url"
```

2021-08-10 06:39 UTC, merged