feat(argocd-image-updater): Add custom environment variables
argoproj/argo-helm pull request #874
Opened 2021-08-17 20:30 UTC by sgavrylenko

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-08-18 07:36 UTC, mkilchhofer requested changes
? I only see Changes in `Chart.yaml`

2021-08-18 21:35 UTC, sgavrylenko commented
@mkilchhofer Sorry, my bad. Fixed

2021-08-19 08:04 UTC, mkilchhofer requested changes
Hi, thanks for your contribution.

Please rework this feature to be aligned with other charts we maintain:

https://github.com/argoproj/argo-helm/blob/b862c6239fa9a6df2f67cdd6a8162001fda42b79/charts/argo-events/values.yaml#L50-L52

https://github.com/argoproj/argo-helm/blob/b862c6239fa9a6df2f67cdd6a8162001fda42b79/charts/argo-events/templates/sensor-controller-deployment.yaml#L39-L41

2021-09-16 16:54 UTC, mkilchhofer approved these changes

2021-09-16 18:56 UTC, mkilchhofer approved these changes

2021-09-16 18:59 UTC, merged