feat(argo-cd): add extraContainers to pods besides server
argoproj/argo-helm pull request #927
Opened 2021-09-11 00:46 UTC by mikutas

Signed-off-by: mikutas <23391543+mikutas@users.noreply.github.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#versioning)
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/argoproj/argo-helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo).
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

Changes are automatically published when merged to `master`. They are not published on branches.

2021-09-12 13:35 UTC, mbevc1 commented
Wouldn't that need to be added outside of current container spec? :thinking:

2021-09-16 17:24 UTC, mkilchhofer requested changes

2021-09-16 17:24 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-application-controller/deployment.yaml
> +{{- toYaml .Values.controller.extraContainers | nindent 6 }}
Please DRY and use:
```suggestion
    {{- with .Values.controller.extraContainers }}
      {{- toYaml . | nindent 6 }}
```

2021-09-16 17:24 UTC, mkilchhofer commented on charts/argo-cd/templates/argocd-repo-server/deployment.yaml
> +{{- toYaml .Values.controller.extraContainers | nindent 6 }}
```suggestion
    {{- with .Values.controller.extraContainers }}
      {{- toYaml . | nindent 6 }}
```

2021-09-16 17:24 UTC, mkilchhofer commented on charts/argo-cd/templates/dex/deployment.yaml
> +{{- toYaml .Values.dex.extraContainers | nindent 6 }}
```suggestion
    {{- with .Values.dex.extraContainers }}
      {{- toYaml . | nindent 6 }}
```

2021-09-16 17:24 UTC, mkilchhofer commented on charts/argo-cd/templates/redis/deployment.yaml
> +{{- toYaml .Values.redis.extraContainers | nindent 6 }}
```suggestion
    {{- with .Values.redis.extraContainers }}
      {{- toYaml . | nindent 6 }}
```

2021-09-16 17:29 UTC, mbevc1 approved these changes

2021-09-16 17:50 UTC, mkilchhofer approved these changes
lgtm

2021-09-16 17:59 UTC, merged